
[font]
size = 14

[font.bold]
family = "PlemolJP35 Console NF"
style = "SemiBold"

[font.bold_italic]
family = "PlemolJP35 Console NF"
style = "SemiBold Italic"

[font.italic]
family = "PlemolJP35 Console NF"
style = "Italic"

[font.normal]
family = "PlemolJP35 Console NF"
style = "Regular"

[terminal.shell]
args = ["-l", "-c", "tmux a -t 0 || tmux"]
program = "/bin/zsh"

[window]
decorations = "full"
opacity = 0.92
startup_mode = "SimpleFullscreen"

[terminal]
